language: generic

sudo: true
git:
  depth: 10

python:
  - "3.5"
  - "3.6"

before_install:
  - sudo apt-get update
  - sudo apt-get install python3
  - pip install coverage codecov pytest>=3.0.5 pytest-cov codacy-coverage # nose>=1.3.7
  - pip install .

script:
  - uname -a
  - which -a vim
  - vim --cmd version --cmd quit
  - ./install.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
