language: generic
sudo: true
git:
  depth: 10

before_install:
  - sudo apt-get update
  - sudo apt-get install python3

install:
  - pip install --upgrade pip
  - pip install coverage

script:
  - uname -a
  - which -a vim
  - vim --cmd version --cmd quit
  - ./install.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
